apiVersion: v1
kind: Service
metadata:
  name: project-elastic-lb
  namespace: default
spec:
  clusterIP: 
  clusterIPs:
  externalIPs:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    role: elastic
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
