apiVersion: v1
kind: Service
metadata:
  name: project-elastic-1
  namespace: default
spec:
  clusterIP: 
  clusterIPs:
  - 
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: project-elastic-1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
