apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: 
  name: elasticsearch
  namespace: default
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    role: elastic
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
