kind: Service
apiVersion: v1
metadata:
  name: project-heartbeat-1
  namespace: default
  labels:
    app: project-heartbeat-1
spec:
  clusterIP:
  selector:
    app: project-heartbeat-1
  ports:
  - name: heartbeat
    port: 5723
    targetPort: 5723
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-heartbeat-1
  namespace: default
  labels:
    role: project-heartbeat-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-heartbeat-1
  template:
    metadata:
      name: project-heartbeat-1
      labels:
        role: project-heartbeat-1
        app: project-heartbeat-1
    spec:
      hostAliases:
      - ip: ""
        hostnames:
        - ""
      nodeSelector:
        kubernetes.io/hostname: 
      volumes:
        - name: project-heartbeat-cm
          configMap:
            name: project-heartbeat-cm
        - name: project-elastic-tls-http
          secret:
            secretName: project-elastic-tls-http
      hostname: project-heartbeat-1
      containers:
        - name: heartbeat
          image: docker.elastic.co/beats/heartbeat:8.12.2
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add:
              - IPC_LOCK
              - SYS_RESOURCE
          env:
            - name: "ELASTICSEARCH_USERNAME"
            - name: "ELASTICSEARCH_PASSWORD"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: "setup.kibana.host"
            - name: "output.elasticsearch.hosts"
            - name: "XPACK_MONITORING_ENABLED"
            - name: "OUTPUT_ELASTICSEARCH_SSL_CERTIFICATE_AUTHORITIES"
            - name: "OUTPUT_ELASTICSEARCH_SSL_CERTIFICATE_VERIFICATION_MODE"
          ports:
            - containerPort: 5723
              name: heartbeat
              protocol: UDP
          volumeMounts:
          - name: project-heartbeat-cm
            subPath: heartbeat.yml
            readOnly: true
          - name: project-elastic-tls-http
