apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: kafka
  name: project-kafka-3
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-kafka-3
      role: kafka
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: project-kafka-3
        role: kafka
      name: project-kafka-3
    spec:
      containers:
      - command:
        - /etc/confluent/docker/run
        env:
        - name: KAFKA_BROKER_ID
        - name: KAFKA_ADVERTISED_HOST_NAME
        - name: KAFKA_ZOOKEEPER_CONNECT
        - name: KAFKA_ADVERTISED_LISTENERS
        - name: KAFKA_BROKER_ID_GENERATION_ENABLE
        - name: KAFKA_OPTS
        - name: KAFKA_HEAP_OPTS
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
        - name: KAFKA_NUM_PARTITIONS
        - name: KAFKA_CONSUMER_TIMEOUT_MS
        - name: KAFKA_LOG_CONNECTION_CLOSE
        image: confluentinc/cp-kafka:7.0.1
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - /usr/bin/kafka-server-stop
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 9092
          timeoutSeconds: 1
        name: cp-kafka
        ports:
        - containerPort: 9092
          name: server
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 9092
          timeoutSeconds: 1
        resources: {}
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: kafka-3-data
      dnsPolicy: ClusterFirst
      hostname: project-kafka-3
      nodeSelector:
        kubernetes.io/hostname: 
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/project-kafka-3
          type: ""
        name: kafka-3-data
