apiVersion: v1
kind: Service
metadata:
  name: project-logstash-lb
  namespace: default
spec:
  clusterIP: 
  clusterIPs:
  - 
  externalIPs:
  - 
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: filebeat
    port: 5044
    protocol: TCP
    targetPort: 5044
  selector:
    role: logstash
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
