apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: logstash
  name: project-logstash-1
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: project-logstash-1
      role: logstash
  template:
    metadata:
      creationTimestamp: null
      labels:
        role: logstash
        app: project-logstash-1
    spec:
      containers:
      - env:
        - name: XPACK_MANAGEMENT_ELASTICSEARCH_USERNAME
        - name: XPACK_MANAGEMENT_ELASTICSEARCH_PASSWORD
        - name: XPACK_MONITORING_ELASTICSEARCH_USERNAME
        - name: XPACK_MONITORING_ELASTICSEARCH_PASSWORD
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: LS_JAVA_OPTS
        - name: ELASTICSEARCH_URL
        - name: HTTP_PORT
        - name: HTTP_HOST
        image: socdev.azurecr.io/logstash_tactical:8.12.2
        imagePullPolicy: IfNotPresent
        name: logstash
        ports:
        - containerPort: 5044
          name: connect
          protocol: TCP
        - containerPort: 9600
          name: api
          protocol: TCP
        resources:
          limits:
            cpu: "12"
            memory: 20Gi
          requests:
            cpu: "1"
            memory: 8Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          name: logstash-1-data
          name: logstash-pipeline
          name: logstash-pipe-conf
          name: project-elastic-tls-http
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: ocp-project-elk-1
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        name: logstash-pipeline
        name: logstash-1-data
        name: logstash-pipe-conf
      - name: project-elastic-tls-http
      - name: project-elastic-tls-node
