apiVersion: v1
kind: Service
metadata:
  name: project-logstash-1
  namespace: default
spec:
  clusterIP: 
  selector:
    app: project-logstash-1
  ports:
  - name: api
    port: 9600
    targetPort: 9600
---
apiVersion: v1
kind: Service
metadata:
  name: project-logstash-2
  namespace: default
spec:
  clusterIP: 
  selector:
    app: project-logstash-2
  ports:
  - name: api
    port: 9600
    targetPort: 9600
---
apiVersion: v1
kind: Service
metadata:
  name: project-logstash-3
  namespace: default
spec:
  clusterIP: 
  selector:
    app: project-logstash-3
  ports:
  - name: api
    port: 9600
    targetPort: 9600
