apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: project-nginx
  name: project-nginx-1
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      role: project-nginx
      app: project-nginx-1
  template:
    metadata:
      creationTimestamp: null
      labels:
        role: project-nginx
        app: project-nginx-1
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: nginx:1.25.4-alpine
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 88
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 88
          name: httphealthz
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /
            port: 88
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 214748364800m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx
          name: project-nginx
          readOnly: true
        - mountPath: /var/log/nginx
          name: project-nginx-log
        - mountPath: /etc/nginx/key/
          name: project-nginx-secret
        - name: project-index
          mountPath: /var/www/index.html
          subPath: index.html
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      nodeSelector:
        kubernetes.io/hostname: ocp-project-elk-1
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: project-nginx-secret
        secret:
          secretName: project-nginx
      - name: project-index
        configMap:
          name: project-index
          items:
            - key: index.html
              path: index.html
      - configMap:
          defaultMode: 420
          name: project-nginx
        name: project-nginx
      - hostPath:
          path: /data/project-nginx-log
          type: ""
        name: project-nginx-log
