apiVersion: apps/v1
kind: Deployment
metadata:
  name: pods-observer
  namespace: default
  labels:
    app: pods-observer
spec:
  revisionHistoryLimit: 10
  replicas: 1
  selector:
    matchLabels:
      app: pods-observer
  template:
    metadata:
      labels:
        app: pods-observer
    spec:
      serviceAccountName: pods-observer
      containers:
      - name: pods-observer
        image: socdev.azurecr.io/pods-observer:1.3
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 9032
          initialDelaySeconds: 30
          periodSeconds: 3600
          timeoutSeconds: 10
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pods-observer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-pods
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pods-observer-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitor-pods
subjects:
- kind: ServiceAccount
  name: pods-observer
  namespace: default
