---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: project-nginx
  namespace: default
spec:
  encryptedData:
    name.key: 
  template:
    metadata:
      creationTimestamp: null
      name: project-nginx
      namespace: default