apiVersion: v1
kind: Service
metadata:
  labels:
    role: project-zookeeper-lb
  name: project-zookeeper-lb
  namespace: default
spec:
  clusterIP: 
  clusterIPs:
  externalIPs:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: connection
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    role: zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
