apiVersion: v1
kind: Service
metadata:
  name: siem-prometheus-lb
  namespace: monitoring
spec:
  clusterIP:
  clusterIPs:
  externalIPs:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
