# clusterissuer-selfsigned.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
#---
#apiVersion: cert-manager.io/v1
#kind: ClusterIssuer
#metadata:
#  name: letsencrypt-prod
#spec:
#  acme:
#    # ACME server URL for Let's Encrypt production environment
#    server: https://acme-v02.api.letsencrypt.org/directory
#    email: test@gmail.com  # Replace with your email
#    privateKeySecretRef:
#      name: letsencrypt-prod-account-key  # Secret where the private key will be stored
#    solvers:
#    - http01:
#        ingress:
#          class: nginx  # Assuming you're using nginx ingress controller

